# github_token Github personal access token, leave this blank or assign a
# dedicated personal access token for this. Required permissions are org:read
# and repo:read. While it's possible to use gitseer without a github token,
# it's recommended to use one to avoid getting any rate limit.
github_token = "ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

# max_worker define how much worker the program will use. Each worker are
# assigned to a goroutine, hence doesn't necessarily maps to 1-on-1 with the
# system threads. 
max_worker = 10

# Available storage_types are ["disk", "memory"], for disk storage_type it's
# required to define the storage_path. Examples:
#
#   storage_type = "memory"
#
# or
#
#   storage_type = "disk"
#   storage_path = "/full/path/to/diretory"
storage_type = "disk"
storage_path = "/home/user/gitseer"

# with_fork if set to true, any forked repository either by organization/user
# will be included in the scan
with_fork = false

# all_branch if set to true, any branch will also be included in scan. else,
# only commits related to HEAD are scanned.
all_branch = false

# [[organization]]
# type = "github"
# name = "traveloka"
# expand_user = true
# expand_repo = true

[[user]]
type = "github"
name = "circleous"